title: Welcome to Rock-Paper-Scissors
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
# baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Rock Paper Scissors
author-img: rock-paper-scissors-logo.png
about-author: A set of essays about Software Engineering practices applied to the development of a Rock-Paper-Scissors game.
social-twitter: pedrozamuner
social-facebook: # add your Facebook handle
social-github: pedrozamuner
social-linkedin: pedro-zamuner
social-email: pedrozamuner@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
